package edu.wctc;

/**
 * One of three possible enemies that cam be generated by EnemyFactory.
 */

public class Goblin extends Enemy
{
    public Goblin()
    {
        setName("Shorty the goblin");
        setPower(10);
        setHealth(63);
    }
}
